version: '3'
services:
  proxy:
    image: traefik
    command: --web --docker --logLevel=INFO
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  client:
    build: ./client
    restart: always
    ports:
      - "8080"
    volumes:
      - ./client:/app
    labels:
      - "traefik.frontend.rule=PathPrefix:/"                           

  server:
    build: ./server
    restart: always
    ports:
      - "8000"
    volumes:
      - ./server:/app
    labels:
      - "traefik.frontend.rule=PathPrefix:/api"
    links:
      - database 

  database:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
